# Generated by Django 3.2.6 on 2022-07-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
