# Generated by Django 3.2.6 on 2022-06-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCateries',
            new_name='ProductCategories',
        ),
    ]
